CREATE TABLE IF NOT EXISTS urls (
  id bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  name VARCHAR(255) UNIQUE NOT NULL,
  created_at DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS url_checks(
  id bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  url_id bigint NOT NULL REFERENCES urls (id) ON DELETE CASCADE,
  status_code INT,
  h1 VARCHAR(255),
  title VARCHAR(255),
  description TEXT,
  created_at DATE NOT NULL
);
